// INVOICES
export const GET_INVOICES = "GET_INVOICES";
export const CLEAR_INVOICES = "CLEAR_INVOICES";
export const CLEAR_STORING_RESULT = "CLEAR_STORING_RESULT";
export const LOADING_INVOICES = "LOADING_INVOICES";
export const STORE_INVOICES = "STORE_INVOICES";
export const LOADING_NEW_INVOICES = "LOADING_NEW_INVOICES";
export const DELETE_INVOICE = "DELETE_INVOICE";
export const GET_CP_ID = "GET_CP_ID";
export const UPDATE_PAYMENT_DETAILS = "UPDATE_PAYMENT_DETAILS";
export const UPDATE_INVOICES_FORM = "UPDATE_INVOICES_FORM";
export const UPDATING_PAYMENTS = "UPDATING_PAYMENTS";
export const SET_PAYMENTS_STATUS = "SET_PAYMENT_STATUS";
export const ADD_DETTAGLIO_PAGAMENTO = "ADD_DETTAGLIO_PAGAMENTO";
export const DELETE_DETTAGLIO_PAGAMENTO = "DELETE_DETTAGLIO_PAGAMENTO";
export const ADD_DATI_PAGAMENTO = "ADD_DATI_PAGAMENTO";
export const UPDATE_DATI_PAGAMENTO = "UPDATE_DATI_PAGAMENTO";
export const CHANGE_ACTIVE_DATI_PAGAMENTO = "CHANGE_ACTIVE_DATI_PAGAMENTO";
export const DELETE_DATI_PAGAMENTO = "DELETE_DATI_PAGAMENTO";
export const SHOW_LAST_INVOICES = "SHOW_LAST_INVOICES";

// PAYMENTS
export const UPDATE_PAYMENTS_FORM = "UPDATE_PAYMENTS_FORM";
export const LOADING_PAYMENTS = "LOADING_PAYMENTS";
export const GET_PAYMENTS = "GET_PAYMENTS";
export const MARK_AS_PAID = "MARK_AS_PAID";

// AUTHENTICATION
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const GET_ROLES = "GET_ROLES";
export const SIGNOUT = "SIGNOUT";
export const UPDATE_SECURITY = "UPDATE_SECURITY";
